"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { products as defaultProducts, type Product } from "@/lib/catalog";

const CART_KEY="bee-girl-shopping-cart", WISH_KEY="bee-girl-wishlist";
const whatsappNumber=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||"919876543210";
const whatsappUrl=`https://wa.me/${whatsappNumber}?text=Hello%20Bee%20Girl%20Shopping%2C%20I%20need%20help%20with%20an%20order.`;
const mapsUrl="https://maps.app.goo.gl/cdn339RiDvj99ikE9?g_st=ac";
const categories=["Kurtis","Sarees","Lehengas","Night Wear"];
function ProductImage({src,alt}:{src:string;alt:string}){const [bad,setBad]=useState(false);return bad?<div className="imageFallback">👗<b>Bee Girl Shopping</b></div>:<img src={src} alt={alt} onError={()=>setBad(true)} loading="lazy"/>;}
export default function Home(){
 const [products,setProducts]=useState<Product[]>(defaultProducts),[wishlist,setWishlist]=useState<number[]>([]),[cartCount,setCartCount]=useState(0),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState(""),[colour,setColour]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[category,setCategory]=useState("All");
 const refresh=()=>{try{const cart=JSON.parse(localStorage.getItem(CART_KEY)||"[]"),wish=JSON.parse(localStorage.getItem(WISH_KEY)||"[]");setCartCount(Array.isArray(cart)?cart.reduce((s:any,i:any)=>s+Number(i.quantity||1),0):0);setWishlist(Array.isArray(wish)?wish.map(Number):[]);}catch{setCartCount(0);setWishlist([])}};
 useEffect(()=>{fetch("/api/products").then(r=>r.ok?r.json():defaultProducts).then(d=>setProducts(Array.isArray(d)&&d.length?d:defaultProducts)).catch(()=>setProducts(defaultProducts));refresh();window.addEventListener("cart-updated",refresh);window.addEventListener("wishlist-updated",refresh);return()=>{window.removeEventListener("cart-updated",refresh);window.removeEventListener("wishlist-updated",refresh)}},[]);
 const visible=useMemo(()=>products.filter(p=>p.active&&(category==="All"||p.category===category)&&`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())),[products,category,search]);
 function toggleWishlist(id:number){const next=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];setWishlist(next);localStorage.setItem(WISH_KEY,JSON.stringify(next));window.dispatchEvent(new Event("wishlist-updated"));}
 function openProduct(p:Product){setSelected(p);setSize(p.sizes[0]||"");setColour(p.colours[0]||"");setNotice("");}
 function addToCart(){if(!selected)return;if(!size||!colour){setNotice("Please select size and colour.");return}let cart:any[]=[];try{const x=JSON.parse(localStorage.getItem(CART_KEY)||"[]");cart=Array.isArray(x)?x:[]}catch{}const found=cart.find(i=>i.id===selected.id&&i.size===size&&i.color===colour);if(found)found.quantity=Number(found.quantity||1)+1;else cart.push({id:selected.id,name:selected.name,category:selected.category,price:selected.price,image:selected.image,size,color:colour,quantity:1});localStorage.setItem(CART_KEY,JSON.stringify(cart));window.dispatchEvent(new Event("cart-updated"));setSelected(null)}
 return <main>
  <div className="topbar"><span>🐝 BEE GIRL SHOPPING</span><span>Women&apos;s Fashion • Anantapur</span></div>
  <header className="header"><div className="headerSide"><Link href="/" className="logoMini"><img src="/products/bee-girl-logo.jpg" alt="Bee Girl Shopping logo"/></Link></div><div className="brand"><span>🌸 Bee Girl Shopping</span><small>Style • Grace • Comfort</small></div><div className="headerSide right"><a href={mapsUrl} target="_blank" rel="noreferrer" className="headBtn location">📍 Location</a><a href={whatsappUrl} target="_blank" rel="noreferrer" className="headBtn whatsapp">💬 WhatsApp</a><Link className="headBtn wish" href="#wishlist">♡ {wishlist.length}</Link><Link className="headBtn cart" href="/cart">🛒 {cartCount}</Link></div></header>
  <section className="hero"><img src="/products/bee-girl-main-header.png" alt="Bee Girl Shopping fashion collection"/></section>
  <section className="intro"><span className="eyebrow">BEE GIRL SHOPPING</span><h1>Beautiful fashion for every occasion</h1><p>Shop elegant kurtis, sarees, lehengas and comfortable night wear from Bee Girl Shopping in Anantapur.</p><button className="primary" onClick={()=>document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"})}>SHOP COLLECTION</button></section>
  <section className="quick"><span><b>👗 Real Clothing Images</b><span>See the product image in every catalogue card</span></span><span><b>♡ Wishlist</b><span>Save your favourite products for later</span></span><span><b>🛒 Easy Cart</b><span>Quantity, remove and total controls</span></span><span><b>🔒 Secure Payment</b><span>Razorpay checkout</span></span></section>
  <section className="categoryNav">{categories.map(c=><button key={c} onClick={()=>{setCategory(c);document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"})}}>{c}</button>)}<button onClick={()=>setCategory("All")}>All Products</button></section>
  <section className="catalog" id="catalog"><div className="sectionHead"><span>OUR COLLECTION</span><h2>{category==="All"?"Shop the collection":category}</h2><p>Choose your favourite design, select size and colour, then add it to your cart.</p></div><div className="tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..."/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="grid">{visible.map(p=><article className="card" key={p.id}><div className="imageWrap"><ProductImage src={p.image} alt={p.name}/><button className={`heart ${wishlist.includes(p.id)?"active":""}`} onClick={()=>toggleWishlist(p.id)}>{wishlist.includes(p.id)?"♥":"♡"}</button></div><div className="cardBody"><span className="category">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="cardBottom"><strong>₹{p.price.toLocaleString("en-IN")}</strong><button onClick={()=>openProduct(p)}>SELECT</button></div></div></article>)}</div>{!visible.length&&<div className="empty">No products found. Try another search.</div>}</section>
  <section className="wishlist" id="wishlist"><div className="sectionHead"><span>YOUR SAVED ITEMS</span><h2>Wishlist</h2><p>{wishlist.length?`${wishlist.length} item(s) saved for later.`:"Tap the heart on any product to save it here."}</p></div>{wishlist.length>0&&<div className="miniGrid">{products.filter(p=>wishlist.includes(p.id)).map(p=><button key={p.id} onClick={()=>openProduct(p)}><ProductImage src={p.image} alt={p.name}/><span>{p.name}</span><b>₹{p.price.toLocaleString("en-IN")}</b></button>)}</div>}</section>
  <footer><div><img src="/products/bee-girl-logo.jpg" alt="Bee Girl Shopping"/><h2>Bee Girl Shopping</h2><p>📍 Sai Nagar, 7th Cross, Anantapur</p></div><div><h3>Customer Support</h3><a href={whatsappUrl} target="_blank" rel="noreferrer">💬 WhatsApp Support</a><a href={mapsUrl} target="_blank" rel="noreferrer">📍 Open Location</a><Link href="/cart">🛒 Cart</Link><Link href="/admin">🔐 Admin</Link></div><small>© 2026 Bee Girl Shopping. All rights reserved.</small></footer>
  {selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><ProductImage src={selected.image} alt={selected.name}/><div><span className="category">{selected.category}</span><h2>{selected.name}</h2><p>{selected.description}</p><strong className="modalPrice">₹{selected.price.toLocaleString("en-IN")}</strong><label>Select Size</label><div className="options">{selected.sizes.map(x=><button key={x} className={size===x?"selected":""} onClick={()=>setSize(x)}>{x}</button>)}</div><label>Select Colour</label><div className="options">{selected.colours.map(x=><button key={x} className={colour===x?"selected":""} onClick={()=>setColour(x)}>{x}</button>)}</div>{notice&&<div className="notice">{notice}</div>}<button className="add" onClick={addToCart}>🛒 ADD TO CART</button></div></div></div>}
 </main>;
}
